netball_visualisation/config/routes.rb
NetballVisualisation::Application.routes.draw do
  resources :stats

  get "home/index"

  root 'home#index'

end

netball_visualisation/app/models/stat.rb
class Stat < ActiveRecord::Base
end

netball_visualisation/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

netball_visualisation/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

netball_visualisation/app/controllers/stats_controller.rb
class StatsController < ApplicationController
  before_action :set_stat, only: [:show, :edit, :update, :destroy]

  # GET /stats
  # GET /stats.json
  def index
    @stats = Stat.all
  end

  # GET /stats/1
  # GET /stats/1.json
  def show
  end

  # GET /stats/new
  def new
    @stat = Stat.new
  end

  # GET /stats/1/edit
  def edit
  end

  # POST /stats
  # POST /stats.json
  def create
    @stat = Stat.new(stat_params)

    respond_to do |format|
      if @stat.save
        format.html { redirect_to @stat, notice: 'Stat was successfully created.' }
        format.json { render action: 'show', status: :created, location: @stat }
      else
        format.html { render action: 'new' }
        format.json { render json: @stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stats/1
  # PATCH/PUT /stats/1.json
  def update
    respond_to do |format|
      if @stat.update(stat_params)
        format.html { redirect_to @stat, notice: 'Stat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stats/1
  # DELETE /stats/1.json
  def destroy
    @stat.destroy
    respond_to do |format|
      format.html { redirect_to stats_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stat
      @stat = Stat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stat_params
      params.require(:stat).permit(:round, :date, :home, :away, :homescore, :awayscore, :homegamepoints, :awaygamepoints, :venue)
    end
end

netball_visualisation/app/helpers/application_helper.rb
module ApplicationHelper
end

netball_visualisation/app/helpers/home_helper.rb
module HomeHelper
end

netball_visualisation/app/helpers/stats_helper.rb
module StatsHelper
end

netball_visualisation/app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

netball_visualisation/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NetballVisualisation</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

netball_visualisation/app/views/stats/_form.html.erb
<%= form_for(@stat) do |f| %>
  <% if @stat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stat.errors.count, "error") %> prohibited this stat from being saved:</h2>

      <ul>
      <% @stat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :round %><br>
    <%= f.number_field :round %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :home %><br>
    <%= f.text_field :home %>
  </div>
  <div class="field">
    <%= f.label :away %><br>
    <%= f.text_field :away %>
  </div>
  <div class="field">
    <%= f.label :homescore %><br>
    <%= f.number_field :homescore %>
  </div>
  <div class="field">
    <%= f.label :awayscore %><br>
    <%= f.number_field :awayscore %>
  </div>
  <div class="field">
    <%= f.label :homegamepoints %><br>
    <%= f.number_field :homegamepoints %>
  </div>
  <div class="field">
    <%= f.label :awaygamepoints %><br>
    <%= f.number_field :awaygamepoints %>
  </div>
  <div class="field">
    <%= f.label :venue %><br>
    <%= f.text_field :venue %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

netball_visualisation/app/views/stats/edit.html.erb
<h1>Editing stat</h1>

<%= render 'form' %>

<%= link_to 'Show', @stat %> |
<%= link_to 'Back', stats_path %>

netball_visualisation/app/views/stats/index.html.erb
<h1>Listing stats</h1>

<table>
  <thead>
    <tr>
      <th>Round</th>
      <th>Date</th>
      <th>Home</th>
      <th>Away</th>
      <th>Homescore</th>
      <th>Awayscore</th>
      <th>Homegamepoints</th>
      <th>Awaygamepoints</th>
      <th>Venue</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stats.each do |stat| %>
      <tr>
        <td><%= stat.round %></td>
        <td><%= stat.date %></td>
        <td><%= stat.home %></td>
        <td><%= stat.away %></td>
        <td><%= stat.homescore %></td>
        <td><%= stat.awayscore %></td>
        <td><%= stat.homegamepoints %></td>
        <td><%= stat.awaygamepoints %></td>
        <td><%= stat.venue %></td>
        <td><%= link_to 'Show', stat %></td>
        <td><%= link_to 'Edit', edit_stat_path(stat) %></td>
        <td><%= link_to 'Destroy', stat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stat', new_stat_path %>

netball_visualisation/app/views/stats/new.html.erb
<h1>New stat</h1>

<%= render 'form' %>

<%= link_to 'Back', stats_path %>

netball_visualisation/app/views/stats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Round:</strong>
  <%= @stat.round %>
</p>

<p>
  <strong>Date:</strong>
  <%= @stat.date %>
</p>

<p>
  <strong>Home:</strong>
  <%= @stat.home %>
</p>

<p>
  <strong>Away:</strong>
  <%= @stat.away %>
</p>

<p>
  <strong>Homescore:</strong>
  <%= @stat.homescore %>
</p>

<p>
  <strong>Awayscore:</strong>
  <%= @stat.awayscore %>
</p>

<p>
  <strong>Homegamepoints:</strong>
  <%= @stat.homegamepoints %>
</p>

<p>
  <strong>Awaygamepoints:</strong>
  <%= @stat.awaygamepoints %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @stat.venue %>
</p>

<%= link_to 'Edit', edit_stat_path(@stat) %> |
<%= link_to 'Back', stats_path %>